/*--------------------------------------------------------------------------*/
/*   /\/\/\__/\/\/\        MooseFactory Foundation - v1.0.0                    */
/*   \/\/\/..\/\/\/                                                         */
/*        |  |             (c)2007-2016 Tristan Leblanc                     */
/*        (oo)             tristan@moosefactory.eu                          */
/* MooseFactory Software                                                    */
/*--------------------------------------------------------------------------*/

/*
 Copyright (c) 2016 Tristan Leblanc - MooseFactory Software <tristan@moosefactory.eu>
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 */


#import "MFResFileLogger.h"

@implementation MFResFileLogger

#pragma mark - Logging

+(void)log:(NSString*)format, ...
{
    va_list argumentList;
    va_start(argumentList, format);
    NSString *string = [[NSString alloc] initWithFormat:format arguments:argumentList];
    [MFResFileLogger logString:string];
    va_end(argumentList);
}

+(void)logToFile:(NSString*)fileName format:(NSString*)format, ...
{
    va_list argumentList;
    va_start(argumentList, format);
    NSString *string = [[NSString alloc] initWithFormat:format arguments:argumentList];
    [MFResFileLogger logString:string file:fileName];
    va_end(argumentList);
}

+(void)logString:(NSString*)string
{
    NSLog(@"%@",string);
}

+(void)logString:(NSString*)string file:(NSString*)fileName
{
    [MFResFileLogger logString:string];
    
    if (fileName) {
        NSString *documentsDirectory = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents"];
        NSString *filePath = [documentsDirectory stringByAppendingPathComponent:fileName];
        
        NSFileHandle *fileHandle = [NSFileHandle fileHandleForUpdatingAtPath:filePath ];
        if (!fileHandle) {
            NSLog(@"MFResFileLogger - Create File \"%@\"",fileName);
            NSError* error = NULL;
            NSString* sep =@"------------------------------------------------------";
            NSString* logHeader = [NSString stringWithFormat:@"%@\r%@\rGenerated by MFResFileLogger\rApplication:%@\rDate : %@\r\r%@\r",sep,fileName,[NSBundle mainBundle].bundleIdentifier,[NSDate date],sep];
            [logHeader writeToFile:filePath atomically:YES encoding:NSUTF8StringEncoding error:&error];
            if (error) {
                NSLog(@"MFResFileLogger - Can't create File \"%@\"\rError : %@",fileName,error.localizedDescription);
                return;
            }
            fileHandle = [NSFileHandle fileHandleForUpdatingAtPath:filePath ];
        }
        if (fileHandle) {
            [fileHandle seekToEndOfFile];
            [fileHandle writeData:  [[string stringByAppendingString:@"\r"] dataUsingEncoding:NSUTF8StringEncoding]];
            [fileHandle closeFile];
        } else {
            NSLog(@"MFResFileLogger - Can't write to file \"%@\"",fileName);
        }
    }
}

#pragma mark - File Utils

+(void)logFile:(NSString*)fileName
{
    if (fileName) {
        NSString *documentsDirectory = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents"];
        NSString *filePath = [documentsDirectory stringByAppendingPathComponent:fileName];
        NSError* error = NULL;
        
        if (!filePath) {
            NSLog(@"MFResFileLogger - File \"%@\" does not exist",fileName);
        } else {
            NSString* content = [NSString stringWithContentsOfFile:filePath encoding:NSUTF8StringEncoding error:&error];
            
            if (error) {
                NSLog(@"MFResFileLogger - logFile \"%@\"- Error - %@",fileName ? fileName : @"NULL",error.localizedDescription);
            } else {
                NSLog(@"\r-----------------------\rMFResFileLogger - Log File : \"%@\"\r%@\r\r-----------------------",fileName,content);
            }
        }
    }

}

+(void)deleteFile:(NSString*)fileName
{
    if (fileName) {
        NSString *documentsDirectory = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents"];
        NSString *filePath = [documentsDirectory stringByAppendingPathComponent:fileName];
        NSError* error = NULL;
        [[NSFileManager defaultManager] removeItemAtPath:filePath error:&error];
    }
}
@end
